### PR TITLE
Fix deviations with missing image data causing crash

### LINKED ISSUE #4: Unclear instruction in gallery nr
In the example
https://backend.deviantart.com/rss.xml?q=gallery:fu51on/27123391

The number 27123391 appears as "gallery" ?

It is not clear where this number (always) stems from ?
•Featured
•Scraps 
seem to relay no number et all ?
What number applies to it ?
Do I even need a number for it ?

F.e. user @swanamii:
https://www.deviantart.com/swanamii/gallery/16690/ocs 
Has a /number/ inb4 ocs ..

But that doesnt apply to all galleries

- Ry3yR

### PR DESCRIPTION
**Pull request by jamesl1001**
This fix should resolve #4; specifically https://github.com/jamesl1001/deviantART-API/issues/4#issuecomment-2049434194

@Ry3yr can you please test this fix and let me know if it works?

### CODE REVIEW

**Comment by Ry3yr** [comment]
If you mean the "null" fix:
https://github.com/jamesl1001/deviantART-API/issues/4#issuecomment-2049434194

It is not yet fixing the issue as I remarked earlier

(However it is good to know that "no image data" submissions cause the failure

**Comment by jamesl1001** [comment]
No, I mean the changes in this pull request

Try to copy these changes into your `getDeviations.php` file and see if that resolves the issue:
https://github.com/jamesl1001/deviantART-API/pull/5/commits/fb03ff19b0fb646833e6c79f278870f42cb7231c?diff=unified&w=0#diff-f724c0063c3e3019e48fee40dd994cebb5f311c91aae7a08a35bc2ff7ad84b15

Otherwise, if you're still getting an error, please share it here.

**Comment by Ry3yr** [comment]
Still having an error sadly:
[16-Apr-2024 15:07:27 UTC] PHP Fatal error:  Uncaught Error: Call to a member function attributes() on null in /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/getDeviations.php:23
Stack trace:
#0 /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/fetch.php(16): getDeviations()
#1 {main}
  thrown in /home/alceawis/public_html/PHP/0demo/2023-12-10-Parse-DA-Gallery-images/deviantART-API/getDeviations.php on line 23

Download (1)

Is the null really enough to catch entries without image data ?
Maybe a preliminary check should be enacted prior fetch ?

**Comment by jamesl1001** [comment]
You now have duplicated `thumbS`, `thumbL` and `image` keys. Delete the first (yellow) set.

322899601-b8c4afdb-418c-4209-aa0c-800f77fd71e0

**Comment by Ry3yr** [comment]
Perfect!

Seems to work now 😻
Download (1)

**Comment by jamesl1001** [comment]
Great, thanks for testing!

**Pull request merged**
